# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
from random import random
from turtledemo.penrose import start

# Import NumPy as its abbreviation 'np'
import numpy as np
from numpy.ma.core import shape, count

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a_1d = np.array(
    [1, 2, 3]
)

# Create a 2-dimensional NumPy array using np.array()
a_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create a 3-dimensional Numpy array using np.array()
a_3d = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
], [
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
], [
    [19, 20, 21],
    [22, 23, 24],
    [25, 26, 27]
]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a_1d.ndim, a_1d.dtype, a_1d.size, a_1d.shape, type(a_1d)

(1, dtype('int64'), 3, (3,), numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a_2d.ndim, a_2d.dtype, a_2d.size, a_2d.shape, type(a_2d)

(2, dtype('int64'), 9, (3, 3), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a_3d.ndim, a_3d.dtype, a_3d.size, a_3d.shape, type(a_3d)

(3, dtype('int64'), 27, (3, 3, 3), numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df_1d = pd.DataFrame(a_1d)
df_1d

0
0  1
1  2
2  3

In [7]:
# Create an array of shape (10, 2) with only ones
a_ones1 = np.ones((10, 2))
a_ones1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
a_zeros = np.zeros((7, 2, 3))
a_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
a_range = np.arange(start=0, stop=100, step=3)
a_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a_random1 = np.random.randint(0, 10, size=(7, 2))
a_random1

array([[7, 9],
       [1, 6],
       [4, 8],
       [1, 1],
       [8, 4],
       [3, 3],
       [9, 9]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a_random2 = np.random.random(size=(3, 5))
a_random2

array([[0.29321195, 0.8746405 , 0.6609842 , 0.40825293, 0.88123036],
       [0.91576087, 0.34034035, 0.617174  , 0.7318877 , 0.48837841],
       [0.27091404, 0.45654117, 0.74965709, 0.26634517, 0.07232676]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a_random3 = np.random.randint(0, 10, size=(4, 6))
a_random3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a_random4 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(a_random4)

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
a_random4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
a_random4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
a_random4[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a_random5 = np.random.randint(0, 10, size=(3, 5))
a_ones2 = np.ones(shape=(3, 5))

In [18]:
# Add the two arrays together
a_ones2 + a_random5

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
a_ones3 = np.ones(shape=(5, 3))
a_ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together
# a_ones3 + a_random5

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
a_ones4 = np.ones(shape=(3, 5))
a_ones4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
a_ones4 - a_random5

array([[-5., -6., -1.,  1., -2.],
       [ 0., -6., -2.,  0., -4.],
       [-4., -8., -2., -4.,  0.]])

In [23]:
# Multiply the ones array with the latest array
a_ones4 * a_random5

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [24]:
# Take the latest array to the power of 2 using '**'
a_random5**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [25]:
# Do the same thing with np.square()
np.square(a_random5)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(a_random4)

np.float64(5.190476190476191)

In [27]:
# Find the maximum of the latest array using np.max()
np.max(a_random5)

np.int64(9)

In [28]:
# Find the minimum of the latest array using np.min()
np.min(a_random5)

np.int64(0)

In [29]:
# Find the standard deviation of the latest array
np.std(a_random5)

np.float64(2.578543947441829)

In [30]:
# Find the variance of the latest array
np.var(a_random5)

np.float64(6.648888888888889)

In [31]:
# Reshape the latest array to (3, 5, 1)
a_random5.reshape(3, 5, 1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [32]:
# Transpose the latest array
a_random5.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a_random6 = np.random.randint(0, 10, size=(3, 3))
a_random7 = np.random.randint(0, 10, size=(3, 2))

In [34]:
# Perform a dot product on the two newest arrays you created
a_random6.dot(a_random7)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a_random8 = np.random.randint(0, 10, size=(4, 3))
a_random9 = np.random.randint(0, 10, size=(4, 3))

In [36]:
# Perform a dot product on the two newest arrays you created
# a_random8.dot(a_random9)

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a_random8.dot(a_random9.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a_random10 = np.random.randint(0, 10, size=(5, 5))
a_random11 = np.random.randint(0, 10, size=(5, 5))

In [39]:
# Compare the two arrays with '>'
a_random10 > a_random11

array([[ True, False,  True,  True, False],
       [ True, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False,  True,  True,  True],
       [False,  True, False,  True, False]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='
a_random10 >= a_random11

array([[ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True, False, False, False,  True],
       [False,  True,  True,  True,  True],
       [False,  True, False,  True, False]])

In [41]:
# Find which elements of the first array are greater than 7
a_random10 > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False, False, False, False]])

In [42]:
# Which parts of each array are equal? (try using '==')
a_random10 == a_random11

array([[False,  True, False, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [56]:
# Sort one of the arrays you just created in ascending order
np.sort(a_random11)

array([[3, 4, 6, 6, 6],
       [1, 2, 5, 8, 9],
       [3, 4, 5, 6, 9],
       [0, 0, 6, 8, 8],
       [2, 3, 6, 8, 8]])

In [57]:
# Sort the indexes of one of the arrays you just created
np.argsort(a_random11)

array([[3, 0, 1, 2, 4],
       [2, 0, 1, 4, 3],
       [2, 0, 1, 4, 3],
       [2, 3, 1, 0, 4],
       [3, 1, 4, 0, 2]])

In [58]:
# Find the index with the maximum value in one of the arrays you've created
np.max(a_random11)

np.int64(9)

In [59]:
# Find the index with the minimum value in one of the arrays you've created
np.min(a_random11)

np.int64(0)

In [61]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a_random11, axis=1)

array([1, 3, 3, 0, 0])

In [62]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a_random11, axis=0)

array([1, 4, 3, 3, 0])

In [66]:
# Create an array of normally distributed random numbers
a_random12 = np.random.randn(3, 5)
a_random12

array([[ 1.94511561, -0.15333646, -0.90698723, -0.81735416, -0.48312268],
       [-0.56982835, -2.09159967,  1.26374053, -0.01548334, -0.02737645],
       [ 0.81787351, -1.05460447, -0.75832712,  0.45741565, -0.06437805]])

In [70]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a_spaced = np.arange(start=1, stop=100, step=10)
a_spaced

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.